import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IconBadge from "./components/IconBadge";
import LogosInstagramIcon from "./icons/LogosInstagramIcon";
import LogosLinkedinIcon from "./icons/LogosLinkedinIcon";
import LogosSpotifyIcon from "./icons/LogosSpotifyIcon";
import LogosTwitter from "./icons/LogosTwitter";
import LogosYoutubeIcon from "./icons/LogosYoutubeIcon";
import Image from "next/image";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aex Properties | We Deliver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sellHouseFooter = [
    "We Buy Any Home",
    "Sell House Fast",
    "Cash House Buyers",
    "Sell Flat Fast",
    "Sell With Tenants",
    "Sell Commercial Property",
  ];

  const generalFooter = [
    "Our Company",
    "How It Works",
    "Meet the Team",
    "Blog",
    "Reviews",
    "Contact Us",
    "Privacy",
    "Complaints",
  ];

  const offersFooter = [
    "Sell House After Divorce",
    "Sell Probate Property",
    "Stop House Repossession",
    "House Sale Fall Through",
    "Moving House",
    "Get A Free Cash Offer",
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          {children}
          {/* footer */}
          <footer className="flex justify-center items-center bg-lightGreen pb-12">
            <div className="mx-24 w-full h-full flex flex-col items-start pt-24 gap-24">
              <div className="flex gap-12 w-full">
                <div className="flex flex-1  flex-col text-darkGreen px-8 gap-6">
                  <p className="font-satoshi font-bold text-3xl">Socials</p>
                  <div className="flex flex-col gap-3 w-fit">
                    <IconBadge>
                      <LogosYoutubeIcon className="text-2xl" />
                    </IconBadge>
                    <IconBadge>
                      <LogosInstagramIcon className="text-3xl" />
                    </IconBadge>
                    <IconBadge>
                      <LogosSpotifyIcon className="text-3xl" />
                    </IconBadge>
                    <IconBadge>
                      <LogosLinkedinIcon className="text-3xl" />
                    </IconBadge>
                    <IconBadge>
                      <LogosTwitter className="text-2xl" />
                    </IconBadge>
                  </div>
                </div>

                <div className="flex flex-1  flex-col text-darkGreen px-8 gap-6">
                  <p className="font-satoshi font-bold text-3xl">Sell House</p>
                  <div className="flex flex-col gap-3 w-full">
                    {sellHouseFooter.map((items, index) => (
                      <div
                        className="cursor-pointer text-darkGreen hover:bg-green-400 transition-all text-base"
                        key={index}
                      >
                        {items}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex flex-1  flex-col text-darkGreen px-8 gap-6">
                  <p className="font-satoshi font-bold text-3xl">General</p>
                  <div className="flex flex-col gap-3 w-full">
                    {generalFooter.map((items, index) => (
                      <div
                        className="cursor-pointer font text-darkGreen hover:bg-green-400 transition-all text-base"
                        key={index}
                      >
                        {items}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex flex-1  flex-col text-darkGreen px-8 gap-6">
                  <p className="font-satoshi font-bold text-3xl">Offers</p>
                  <div className="flex flex-col gap-3 w-full">
                    {offersFooter.map((items, index) => (
                      <div
                        className="cursor-pointer font text-darkGreen hover:bg-green-400 transition-all text-base"
                        key={index}
                      >
                        {items}
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex justify-center items-center w-full">
                <Image
                  priority={true}
                  alt="AEX Properties Logo image"
                  width={2000}
                  height={1000}
                  src={"/images/AEX PROPERTIES/footer_darkgreen.png"}
                  className="object-contain w-full h-auto"
                />
              </div>
            </div>
          </footer>
        </>
      </body>
    </html>
  );
}
